name: petperfect
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  stacked: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
